allowBuilds:
  '@parcel/watcher': true
  core-js-pure: true
  unrs-resolver: true
  yarn: true

minimumReleaseAgeExclude:
  - '@lazy-node/semver-ampersand@3.0.11'
  - '@lazy-node/semver-part@1.0.27'
  - '@lazy-node/semver-simple-parse@4.0.8'
  - '@yarn-tool/changelog@3.0.14'
  - '@yarn-tool/detect-package-manager@1.0.10'
  - '@yarn-tool/detect-yarnlock-version@2.0.10'
  - '@yarn-tool/find-root@2.0.25'
  - '@yarn-tool/fix-all@3.0.17 || 3.0.19'
  - '@yarn-tool/fix-ws-versions@3.0.11'
  - '@yarn-tool/fnm-detect@1.0.8'
  - '@yarn-tool/get-global-dirs@1.0.6'
  - '@yarn-tool/get-paths-by-type@2.0.19'
  - '@yarn-tool/init-path@2.0.10'
  - '@yarn-tool/is-builtin-module@1.0.28'
  - '@yarn-tool/is-npx@1.0.27'
  - '@yarn-tool/ncu-ws@2.0.12'
  - '@yarn-tool/ncu@3.0.10'
  - '@yarn-tool/node-modules-link@3.0.12'
  - '@yarn-tool/node-modules@3.0.12'
  - '@yarn-tool/normalize-deps-value@2.0.9'
  - '@yarn-tool/npm-package-arg-util@2.0.8'
  - '@yarn-tool/pkg-deps-add@3.0.10'
  - '@yarn-tool/pkg-deps-util@3.0.10'
  - '@yarn-tool/pkg-entry-util@3.0.14'
  - '@yarn-tool/pkg-git-info@2.0.8'
  - '@yarn-tool/pkg-hosted-info@3.0.11'
  - '@yarn-tool/pkg-name-util@1.0.12'
  - '@yarn-tool/pkg-readme-tpl@1.0.9'
  - '@yarn-tool/pkg-version-query@3.0.10'
  - '@yarn-tool/require-resolve@4.0.9'
  - '@yarn-tool/resolve-package@3.0.10'
  - '@yarn-tool/search-workspace-prefix-by-name@2.0.10'
  - '@yarn-tool/semver-diff@2.0.21'
  - '@yarn-tool/setup-module-env@3.0.14 || 3.0.15'
  - '@yarn-tool/sort-lerna-json@3.0.11'
  - '@yarn-tool/sort-package-json-exports@1.0.8'
  - '@yarn-tool/sort-package-json-order@2.0.6'
  - '@yarn-tool/static-file@3.0.17 || 3.0.18'
  - '@yarn-tool/table@2.0.22'
  - '@yarn-tool/types@1.0.21'
  - '@yarn-tool/update-notifier@1.0.48'
  - '@yarn-tool/validate-npm-package-name@3.0.25'
  - '@yarn-tool/version-recommended@3.0.15'
  - '@yarn-tool/workspaces-project@3.0.14'
  - '@yarn-tool/write-package-json@1.0.17'
  - '@yarn-tool/ws-find-up-paths@1.0.22'
  - '@yarn-tool/ws-scope@3.0.11'
  - '@yarn-tool/yargs-util@1.0.16'
  - '@yarn-tool/yarn-struct-utils@2.0.10'
  - '@yarn-tool/yarnlock-banner@2.0.6'
  - '@yarn-tool/yarnlock-dedupe@2.0.11'
  - '@yarn-tool/yarnlock-diff@3.0.10'
  - '@yarn-tool/yarnlock-entries@3.0.11'
  - '@yarn-tool/yarnlock-error@1.0.22'
  - '@yarn-tool/yarnlock-fs@3.0.11'
  - '@yarn-tool/yarnlock-ncu@3.0.12'
  - '@yarn-tool/yarnlock-parse-assert@2.0.11'
  - '@yarn-tool/yarnlock-parse-raw@2.0.9'
  - '@yarn-tool/yarnlock-parse@3.0.11'
  - '@yarn-tool/yarnlock-parsed-to-json@2.0.11'
  - '@yarn-tool/yarnlock-stringify@2.0.11'
  - '@yarn-tool/yarnlock-types@2.0.8'
  - '@yarn-tool/yarnlock-util@3.0.10'
  - '@yarn-tool/yarnlock@3.0.10'
  - cache-path@4.0.12
  - create-yarn-workspaces@3.0.19 || 3.0.21
  - find-pkg-ws@1.0.54
  - find-yarn-workspace-root2@1.2.55
  - npm-init2@3.0.19 || 3.0.21
  - npm-package-json-loader@3.0.15
  - sort-package-json-scripts@1.1.34
  - sort-package-json3@3.0.12
  - workspaces-config@2.0.11
  - ws-pkg-list@3.0.11
  - ws-root-spawn@1.0.55 || 1.0.56
  - '@types/node@26.5.0'
